### PR TITLE
rename EXPORT to LIBXMP_EXPORT

### PR DESCRIPTION
**Pull request by sezero**
EXPORT is a dangerously common name

### CODE REVIEW

**Comment by sezero** [comment]
PING ?

**Comment by sezero** [comment]
PING

**Comment by cmatsuoka** [comment]
Hi,

Pong. I'm alive, just a bit troubled right now but I'll merge the requests
ASAP :)

Thanks!

**Comment by cmatsuoka** [comment]
Merged, thanks.

**Pull request merged**
